# Generated by Claude
"""
Custom exceptions for parser operations.
"""


class ParseError(Exception):
    """Raised when parsing fails."""


class InvalidJavaSourceError(ParseError):
    """Raised when Java source code is invalid or cannot be parsed."""


class JavaDocParseError(Exception):
    """Raised when Javadoc parsing fails."""
