# Example configuration for JavaMCP Server
# Copy this file to config.yaml and adjust for your needs

# Server configuration
server:
  mode: stdio  # Server mode: "stdio" or "http"
  host: localhost  # Host for HTTP mode
  port: 8000  # Port for HTTP mode

# Repository configuration
repositories:
  urls:
    - https://github.com/apache/commons-lang.git
    - https://github.com/google/guava.git
  local_base_path: ./repositories  # Local directory for cloned repos
  branch: main  # Default branch to use

# Logging configuration
logging:
  level: INFO  # Log level: DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  output: console  # Output: "console", "file", or "both"
  file_path: null  # Log file path (required if output is "file" or "both")

# Parser configuration (optional)
# parser:
#   timeout: 30  # Parse timeout in seconds
#   skip_test_files: true  # Skip test files during parsing
