# Generated by Claude
"""
Unit tests for JavaMCP FastMCP server.
"""

from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

from javamcp.config.schema import ApplicationConfig, RepositoryConfig
from javamcp.indexer.indexer import APIIndexer
from javamcp.indexer.query_engine import QueryEngine
from javamcp.models.java_entities import JavaClass
from javamcp.repository.manager import RepositoryManager
from javamcp.server import get_state, initialize_server, mcp


class TestFastMCPServer:
    """Tests for FastMCP server implementation."""

    @patch.object(RepositoryManager, "initialize_repositories")
    @patch("javamcp.server.load_config")
    def test_initialize_server(self, mock_load_config, mock_init_repos):
        """Test server initialization."""
        mock_config = ApplicationConfig(
            repositories=RepositoryConfig(
                urls=["https://github.com/example/repo.git"],
                local_base_path="/tmp/repos",
            )
        )
        mock_load_config.return_value = mock_config

        # Reset state first
        state = get_state()
        state.initialized = False
        state.config = None
        state.repository_manager = None
        state.indexer = None
        state.query_engine = None

        initialize_server()

        mock_load_config.assert_called_once_with(None)
        mock_init_repos.assert_called_once()

        state = get_state()
        assert state.initialized
        assert state.config is not None
        assert isinstance(state.repository_manager, RepositoryManager)
        assert isinstance(state.indexer, APIIndexer)
        assert isinstance(state.query_engine, QueryEngine)

    @patch.object(RepositoryManager, "initialize_repositories")
    @patch("javamcp.server.load_config")
    def test_initialize_server_with_config_path(
        self, mock_load_config, mock_init_repos
    ):
        """Test server initialization with custom config path."""
        mock_config = ApplicationConfig(
            repositories=RepositoryConfig(
                urls=["https://github.com/example/repo.git"],
                local_base_path="/tmp/repos",
            )
        )
        mock_load_config.return_value = mock_config

        # Reset state first
        state = get_state()
        state.initialized = False

        initialize_server("/path/to/config.yaml")

        mock_load_config.assert_called_once_with("/path/to/config.yaml")
        assert get_state().initialized

    def test_get_state(self):
        """Test getting server state."""
        state = get_state()

        assert state is not None
        assert hasattr(state, "config")
        assert hasattr(state, "repository_manager")
        assert hasattr(state, "indexer")
        assert hasattr(state, "query_engine")
        assert hasattr(state, "initialized")

    def test_mcp_instance_exists(self):
        """Test that FastMCP instance is created."""
        assert mcp is not None
        # Check that tools are registered
        # Note: FastMCP doesn't expose tools directly, so we just verify instance exists

    @patch.object(RepositoryManager, "initialize_repositories")
    @patch("javamcp.server.load_config")
    def test_state_shared_across_tools(self, mock_load_config, mock_init_repos):
        """Test that state is shared across all tools."""
        mock_config = ApplicationConfig(
            repositories=RepositoryConfig(
                urls=["https://github.com/example/repo.git"],
                local_base_path="/tmp/repos",
            )
        )
        mock_load_config.return_value = mock_config

        # Reset and initialize
        state = get_state()
        state.initialized = False

        initialize_server()

        # Get state again
        state2 = get_state()

        # Should be the same instance
        assert state is state2
        assert state2.initialized


class TestFastMCPTools:
    """Tests for FastMCP tool decorators."""

    def test_search_methods_tool_exists(self):
        """Test that search_methods tool is registered."""
        # Import the tool function from server module
        from javamcp.server import search_methods

        assert search_methods is not None
        # FastMCP wraps functions in FunctionTool, so check for that
        assert hasattr(search_methods, "__name__") or hasattr(search_methods, "name")

    def test_analyze_class_tool_exists(self):
        """Test that analyze_class tool is registered."""
        from javamcp.server import analyze_class

        assert analyze_class is not None
        assert hasattr(analyze_class, "__name__") or hasattr(analyze_class, "name")

    def test_extract_apis_tool_exists(self):
        """Test that extract_apis tool is registered."""
        from javamcp.server import extract_apis

        assert extract_apis is not None
        assert hasattr(extract_apis, "__name__") or hasattr(extract_apis, "name")

    def test_generate_guide_tool_exists(self):
        """Test that generate_guide tool is registered."""
        from javamcp.server import generate_guide

        assert generate_guide is not None
        assert hasattr(generate_guide, "__name__") or hasattr(generate_guide, "name")
