# Generated by Claude
"""
Custom exceptions for indexer operations.
"""


class IndexNotBuiltError(Exception):
    """Raised when attempting to query an index that hasn't been built."""


class ClassNotFoundError(Exception):
    """Raised when a class is not found in the index."""


class MethodNotFoundError(Exception):
    """Raised when a method is not found in the index."""


class RepositoryNotIndexedError(Exception):
    """Raised when a repository has not been indexed."""
