# Generated by Claude
"""
Base class for JavaParser (ANTLR4 generated parser may reference this).
"""

from antlr4 import Parser


class JavaParserBase(Parser):
    """Base class for Java parser."""

    pass
