# Generated by Claude
"""
JavaMCP - MCP server for exposing Java APIs with Javadoc context.

A Python-based MCP (Model Context Protocol) server that provides AI coding
assistants with rich contextual information about Java APIs, including
Javadocs, method signatures, class hierarchies, and usage examples.
"""

__version__ = "0.1.0"
__author__ = "JavaMCP Contributors"

from javamcp.server import JavaMCPServer, create_server

__all__ = [
    "JavaMCPServer",
    "create_server",
    "__version__",
]
