# Generated by Claude
"""
Git repository management functionality.
"""

from .exceptions import (CloneFailedError, GitOperationError,
                         InvalidRepositoryError, RepositoryNotFoundError)
from .git_operations import (checkout_branch, clone_repository,
                             get_current_commit_hash, is_git_repository,
                             pull_repository)
from .manager import RepositoryManager

__all__ = [
    # Exceptions
    "RepositoryNotFoundError",
    "CloneFailedError",
    "InvalidRepositoryError",
    "GitOperationError",
    # Git operations
    "clone_repository",
    "pull_repository",
    "checkout_branch",
    "is_git_repository",
    "get_current_commit_hash",
    # Manager
    "RepositoryManager",
]
