# Generated by Claude
"""
Custom exceptions for repository operations.
"""


class RepositoryNotFoundError(Exception):
    """Raised when a repository is not found at the specified location."""


class CloneFailedError(Exception):
    """Raised when cloning a repository fails."""


class InvalidRepositoryError(Exception):
    """Raised when a path does not contain a valid Git repository."""


class GitOperationError(Exception):
    """Raised when a Git operation fails."""
